import { useMemo, useState } from "react";
import { Link, Navigate } from "react-router-dom";
import { loadAdminSession } from "../Auth/adminAuthStorage";
import {
  getNotificationCategory,
  getNotificationCategoryLabel,
  getNotificationsForUser,
} from "../../Profile/notificationsStorage";

const FILTERS = [
  { key: "all", label: "All" },
  { key: "orders", label: "Orders" },
  { key: "shipping", label: "Shipping" },
  { key: "announcement", label: "Announcement" },
  { key: "more", label: "More" },
];

const READ_FILTERS = [
  { key: "all", label: "All" },
  { key: "unread", label: "Unread" },
  { key: "read", label: "Read" },
];

function formatDate(value) {
  if (!value) {
    return "Recently";
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(new Date(value));
}

function AdminNotificationsPage({
  notifications = [],
  notificationsLoading = false,
  notificationsError = "",
  authUser = null,
}) {
  const session = loadAdminSession() ?? authUser;
  const [searchTerm, setSearchTerm] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [readFilter, setReadFilter] = useState("all");

  if (!session) {
    return <Navigate to="/admin/login" replace />;
  }

  const visibleNotifications = useMemo(
    () =>
      getNotificationsForUser(notifications, session)
        .slice()
        .sort(
          (left, right) =>
            new Date(right.createdAt ?? 0) - new Date(left.createdAt ?? 0),
        ),
    [notifications, session],
  );

  const filteredNotifications = useMemo(() => {
    const term = searchTerm.trim().toLowerCase();

    return visibleNotifications.filter((notification) => {
      const category = getNotificationCategory(notification);
      const isUnread = !(notification.isRead ?? notification.read);
      const blob = [
        notification.customerName,
        notification.customerEmail,
        notification.title,
        notification.message,
        notification.orderNumber,
        notification.batchNumber,
        notification.paymentReference,
        notification.actionLabel,
      ]
        .filter(Boolean)
        .join(" ")
        .toLowerCase();

      const matchesSearch = !term || blob.includes(term);
      const matchesCategory = categoryFilter === "all" || category === categoryFilter;
      const matchesRead =
        readFilter === "all" ||
        (readFilter === "read" && !isUnread) ||
        (readFilter === "unread" && isUnread);

      return matchesSearch && matchesCategory && matchesRead;
    });
  }, [categoryFilter, readFilter, searchTerm, visibleNotifications]);

  const totalNotifications = visibleNotifications.length;
  const unreadNotifications = visibleNotifications.filter(
    (item) => !(item.isRead ?? item.read),
  ).length;
  const orderNotifications = visibleNotifications.filter(
    (item) => getNotificationCategory(item) === "orders",
  ).length;
  const shippingNotifications = visibleNotifications.filter(
    (item) => getNotificationCategory(item) === "shipping",
  ).length;

  return (
    <main className="admin-support-page">
      <section className="admin-support-shell">
        <header className="admin-support-header">
          <div>
            <p>Admin inbox</p>
            <h1>Notifications</h1>
            <span>Read shipment, payment, and order notifications generated by the live store flows.</span>
          </div>

          <div className="admin-support-header__actions">
            <Link
              to="/admin/dashboard"
              className="admin-support-header__button admin-support-header__button--ghost"
            >
              Back to dashboard
            </Link>
          </div>
        </header>

        <section className="admin-support-summary">
          <article className="admin-support-metric">
            <span>Total Notifications</span>
            <strong>{totalNotifications}</strong>
            <small>All records visible to the admin account.</small>
          </article>
          <article className="admin-support-metric">
            <span>Unread</span>
            <strong>{unreadNotifications}</strong>
            <small>Notifications waiting to be reviewed.</small>
          </article>
          <article className="admin-support-metric">
            <span>Order Updates</span>
            <strong>{orderNotifications}</strong>
            <small>Order and payment-related updates.</small>
          </article>
          <article className="admin-support-metric">
            <span>Shipping Updates</span>
            <strong>{shippingNotifications}</strong>
            <small>Shipment events and delivery progress.</small>
          </article>
        </section>

        <section className="admin-support-panel">
          <div className="admin-support-toolbar">
            <label className="admin-support-search" htmlFor="admin-notification-search">
              <span>Search</span>
              <input
                id="admin-notification-search"
                type="search"
                value={searchTerm}
                onChange={(event) => setSearchTerm(event.target.value)}
                placeholder="Search customer, title, or message"
              />
            </label>

            <label className="admin-support-filter" htmlFor="admin-notification-category">
              <span>Category</span>
              <select
                id="admin-notification-category"
                value={categoryFilter}
                onChange={(event) => setCategoryFilter(event.target.value)}
              >
                {FILTERS.map((filter) => (
                  <option key={filter.key} value={filter.key}>
                    {filter.label}
                  </option>
                ))}
              </select>
            </label>

            <label className="admin-support-filter" htmlFor="admin-notification-read">
              <span>Status</span>
              <select
                id="admin-notification-read"
                value={readFilter}
                onChange={(event) => setReadFilter(event.target.value)}
              >
                {READ_FILTERS.map((filter) => (
                  <option key={filter.key} value={filter.key}>
                    {filter.label}
                  </option>
                ))}
              </select>
            </label>
          </div>

          {notificationsLoading ? (
            <p className="admin-support-empty">Loading notifications...</p>
          ) : notificationsError ? (
            <p className="admin-support-error">{notificationsError}</p>
          ) : null}

          <div className="admin-support-table-wrap">
            <table className="admin-support-table">
              <thead>
                <tr>
                  <th>Customer</th>
                  <th>Title</th>
                  <th>Category</th>
                  <th>Status</th>
                  <th>Date</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {!notificationsLoading && !notificationsError && filteredNotifications.length > 0 ? (
                  filteredNotifications.map((notification) => {
                    const isUnread = !(notification.isRead ?? notification.read);
                    const category = getNotificationCategory(notification);

                    return (
                      <tr key={notification.id} className="admin-support-row">
                        <td>
                          <strong>{notification.customerName || "Customer"}</strong>
                          <small>{notification.customerEmail || "No email captured"}</small>
                        </td>
                        <td>
                          <strong>{notification.title}</strong>
                          <small>{notification.message}</small>
                        </td>
                        <td>
                          <strong>{getNotificationCategoryLabel(category)}</strong>
                          <small>{notification.orderNumber || notification.batchNumber || notification.paymentReference || notification.sourceType}</small>
                        </td>
                        <td>
                          <strong>{isUnread ? "Unread" : "Read"}</strong>
                          <small>{isUnread ? "Waiting for review" : "Already opened"}</small>
                        </td>
                        <td>
                          <strong>{formatDate(notification.createdAt)}</strong>
                          <small>{notification.actionDescription || "Supabase notification"}</small>
                        </td>
                        <td>
                          <div className="admin-support-actions">
                            {notification.actionUrl ? (
                              <Link
                                to={notification.actionUrl}
                                className="admin-support-action admin-support-action--primary"
                              >
                                {notification.actionLabel || "Open"}
                              </Link>
                            ) : (
                              <span className="admin-support-action admin-support-action--ghost">
                                No link
                              </span>
                            )}
                          </div>
                        </td>
                      </tr>
                    );
                  })
                ) : (
                  !notificationsLoading &&
                  !notificationsError && (
                    <tr className="admin-support-empty-row">
                      <td colSpan="6">
                        <div className="admin-support-empty">
                          <h2>No notifications found.</h2>
                          <p>Try another search term or change the filters.</p>
                        </div>
                      </td>
                    </tr>
                  )
                )}
              </tbody>
            </table>
          </div>
        </section>
      </section>
    </main>
  );
}

export default AdminNotificationsPage;
